### ISSUE TITLE
Not working in angular v11

### ISSUE THREAD

**Issue by mdarmousa** [fusioncharts/angular-fusioncharts#106]
Warning: Entry point '@angular/core' contains deep imports into 'D:/TestProjects/chart-proj/node_modules/angular-fusioncharts/node_modules/rxjs/Observable', 'D:/TestProjects/chart-proj/node_modules/angular-fusioncharts/node_modules/rxjs/observable/merge', 'D:/TestProjects/chart-proj/node_modules/angular-fusioncharts/node_modules/rxjs/operator/share', 'D:/TestProjects/chart-proj/node_modules/angular-fusioncharts/node_modules/rxjs/Subject'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Compiling @angular/core : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Error: Error on worker #2: TypeError: Cannot read property 'fileName' of null
    at Object.getImportRewriter (D:\TestProjects\chart-proj\node_modules\@angular\compiler-cli\ngcc\src\rendering\utils.js:23:72)
    at DtsRenderer.renderDtsFile (D:\TestProjects\chart-proj\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:77:72)
    at D:\TestProjects\chart-proj\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:69:134
    at Map.forEach (<anonymous>)
    at DtsRenderer.renderProgram (D:\TestProjects\chart-proj\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:69:26)
    at Transformer.transform (D:\TestProjects\chart-proj\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:88:52)
    at D:\TestProjects\chart-proj\node_modules\@angular\compiler-cli\ngcc\src\execution\create_compile_function.js:52:42
    at D:\TestProjects\chart-proj\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\worker.js:85:54
    at step (D:\TestProjects\chart-proj\node_modules\tslib\tslib.js:143:27)
    at Object.next (D:\TestProjects\chart-proj\node_modules\tslib\tslib.js:124:57)
    at ClusterMaster.onWorkerMessage (D:\TestProjects\chart-proj\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:195:27)
    at D:\TestProjects\chart-proj\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (D:\TestProjects\chart-proj\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (D:\TestProjects\chart-proj\node_modules\tslib\tslib.js:143:27)
    at Object.next (D:\TestProjects\chart-proj\node_modules\tslib\tslib.js:124:57)
    at D:\TestProjects\chart-proj\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\TestProjects\chart-proj\node_modules\tslib\tslib.js:113:16)
    at EventEmitter.<anonymous> (D:\TestProjects\chart-proj\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:287:32)
    at EventEmitter.emit (events.js:315:20)
An unhandled exception occurred: NGCC failed.
See "C:\Users\mdarm\AppData\Local\Temp\ng-RFcWjs\angular-errors.log" for further details.

**Comment by AyanBhadury** [comment]
Please use angular-fusioncharts : 3.0.4

**Comment by mdarmousa** [comment]
> Please use angular-fusioncharts : 3.0.4

Same :/

**Comment by AyanBhadury** [comment]
https://github.com/AyanBhadury/angular-fusioncharts-demo

You can clone the repo and test it
