### ISSUE TITLE
Fusion Charts not working with Angular 12

### ISSUE THREAD

**Issue by jaimecigna** [fusioncharts/angular-fusioncharts#123]
`Error: Error on worker #2: TypeError: Cannot read property 'fileName' of null
    at Object.getImportRewriter (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@angular/compiler-cli/ngcc/src/rendering/utils.js:23:72)
    at DtsRenderer.renderDtsFile (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@angular/compiler-cli/ngcc/src/rendering/dts_renderer.js:77:72)
    at /Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@angular/compiler-cli/ngcc/src/rendering/dts_renderer.js:69:158
    at Map.forEach (<anonymous>)
    at DtsRenderer.renderProgram (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@angular/compiler-cli/ngcc/src/rendering/dts_renderer.js:69:26)
    at Transformer.transform (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@angular/compiler-cli/ngcc/src/packages/transformer.js:93:52)
    at /Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@angular/compiler-cli/ngcc/src/execution/create_compile_function.js:52:42
    at /Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:85:54
    at step (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/tslib/tslib.js:124:57)
    at ClusterMaster.onWorkerMessage (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:195:27)
    at /Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
    at ClusterMaster.<anonymous> (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
    at step (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/tslib/tslib.js:124:57)
    at /Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/tslib/tslib.js:113:16)
    at EventEmitter.<anonymous> (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:287:32)
    at EventEmitter.emit (events.js:315:20)
/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@ngtools/webpack/src/ngcc_processor.js:129
            throw new Error(errorMessage + `NGCC failed${errorMessage ? ', see above' : ''}.`);
            ^

Error: NGCC failed.
    at NgccProcessor.process (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@ngtools/webpack/src/ngcc_processor.js:129:19)
    at /Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/@ngtools/webpack/src/ivy/plugin.js:110:27
    at Hook.eval [as call] (eval at create (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:18:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/webpack/lib/Compiler.js:1033:30)
    at /Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/webpack/lib/Compiler.js:1076:29
    at Hook.eval [as callAsync] (eval at create (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/webpack/lib/Compiler.js:1071:28)
    at /Users/someone/Desktop/htdocs/cmp-ebh-app/node_modules/webpack/lib/Watching.js:188:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cmp-ebh-app@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cmp-ebh-app@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/someone/.npm/_logs/2021-06-30T20_45_38_756Z-debug.log`

**Comment by nicks258** [comment]
getting same problem
