### ISSUE TITLE
Fusion Charts not rendering in Angular 17 ESBuild

### ISSUE THREAD

**Issue by schaefro63** [fusioncharts/angular-fusioncharts#184]
Compiling project in Angular 17 using esbuild the charts don't render. The following exception stack can be seen in chrome debug console. 

ERROR TypeError: t is not a function
at main-FDVUKKK2.js:250:138026
at Array.forEach ()
at o.resolveFusionCharts (main-FDVUKKK2.js:250:137957)
at new o (main-FDVUKKK2.js:250:137650)
at o.ɵfac [as factory] (main-FDVUKKK2.js:250:138247)
at em (main-FDVUKKK2.js:241:17093)
at aU (main-FDVUKKK2.js:241:16602)
at lM (main-FDVUKKK2.js:241:16331)
at sM (main-FDVUKKK2.js:241:15852)
at Be (main-FDVUKKK2.js:241:54171)

**Comment by schaefro63** [comment]
Angular 17.1.2
angular/fusioncharts: 4.0.3
fusioncharts: 3.21.1

**Comment by mithusingh32** [comment]
We had it compile in our project. But the chart would only render about 10% of the time. 
I don't have high hopes for Fusioncharts to actually update this library for esbuild.

**Comment by leonetosoft** [comment]
same problem here

**Comment by rnogueira-namoadigital** [comment]
same problem here

**Comment by simondingle** [comment]
+1

**Comment by schaefro63** [comment]
Opened a ticket with fusion charts support 7 months ago. 
https://support.fusioncharts.com/support/tickets/539635
