### ISSUE TITLE
Charts break when refreshing on angular 16, 

### ISSUE THREAD

**Issue by daddyschmack** [fusioncharts/angular-fusioncharts#185]
We have a multi-chart page.. everything loads correctly on intial load.. But when we click the refresh button, all the charts go from being "side by side" to one on each row..
This did not happen before the upgrade

Angular 16.2.12
Angular FusionCharts 4.03

error below:
default-src_app_modules_shared_module_ts-webpack_sharing_consume_default_ddc_app-service_ddc_-cb1f41.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'data')
    at FusionChartsComponent.ngDoCheck (fusioncharts.component.js:285:51)
    at callHookInternal (core.mjs:4024:14)
    at callHook (core.mjs:4055:9)
    at callHooks (core.mjs:4006:17)
    at executeInitAndCheckHooks (core.mjs:3956:9)
    at refreshView (core.mjs:13513:21)
    at detectChangesInView (core.mjs:13663:9)
    at detectChangesInEmbeddedViews (core.mjs:13606:13)
    at refreshView (core.mjs:13522:9)
    at detectChangesInView (core.mjs:13663:9)

**Comment by mithusingh32** [comment]
FusionCharts can be very fragile for Angular. How are you loading the fusioncharts? 
What we do is explicitly call a render function the chart, after have verified we have gotten all the data. Even then we have all our charting component lazy loaded.
