### ISSUE TITLE
Angular Fusion Charts does not work bulding with Angular ESBuild

### ISSUE THREAD

**Issue by rnogueira-namoadigital** [fusioncharts/angular-fusioncharts#192]
I cloned the project and changed the anguar.json builder from

`@angular-devkit/build-angular:browser` to `@angular-devkit/build-angular:browser-esbuild`

After build and run, I got this error on browser:

```
main.ts:11 ERROR TypeError: FusionChartsModules is not a function
    at fusioncharts.service.ts:55:11
    at Array.forEach (<anonymous>)
    at _a45.resolveFusionCharts (fusioncharts.service.ts:48:15)
    at new _a45 (fusioncharts.service.ts:37:10)
    at NodeInjectorFactory._a45_Factory [as factory] (ɵfac.js:1:1)
    at getNodeInjectable (core.mjs:5984:44)
    at searchTokensOnInjector (core.mjs:5911:16)
    at lookupTokenUsingNodeInjector (core.mjs:5860:34)
    at getOrCreateInjectable (core.mjs:5772:23)
    at ɵɵdirectiveInject (core.mjs:11050:19)
```

Since ESBuild is the default Angular Build, we need some attention in this issue as soon as possible.

**Comment by Somibandaru** [comment]
have you found a way to solve this issue , im currently using angular 20 and im getting the same error

**Comment by rnogueira-namoadigital** [comment]
> have you found a way to solve this issue , im currently using angular 20 and im getting the same error

try changing imports 

from:
```
import * as FusionCharts from "fusioncharts";
import * as charts from "fusioncharts/fusioncharts.charts";
```

to:
```
import FusionCharts from 'fusioncharts';
import charts from 'fusioncharts/fusioncharts.charts';
```
