### ISSUE TITLE
Errors when I replace the trial js files with latest licensed js files

### ISSUE THREAD

**Issue by JasonHaley** [fusioncharts/angular-fusioncharts#3]
I am getting and error when I run the angular2-seed-fusioncharts sample (as well as my work project) when I replace the trial js files for fusionscharts with the licensed version of the js files.

Any idea on how I can resolve this?  Has anyone tried getting the angular2 stuff running with licensed versions of the js files?  If so can you tell me what you did?

The errors I am getting are:
Uncaught TypeError: Cannot read property 'test' of undefined
    at Object.<anonymous> (http://localhost:3000/main.bundle.js:68684:135)
    at Function.p.core (http://localhost:3000/main.bundle.js:66834:18)
    at Function.module (http://localhost:3000/main.bundle.js:66833:274)
    at Function.register (http://localhost:3000/main.bundle.js:66836:387)
    at http://localhost:3000/main.bundle.js:68683:125
    at http://localhost:3000/main.bundle.js:62464:13
    at Array.forEach (native)
    at Function.FusionChartsModule.forRoot (http://localhost:3000/main.bundle.js:62463:29)
    at http://localhost:3000/main.bundle.js:63066:60
    at Object.<anonymous> (http://localhost:3000/main.bundle.js:63077:2)
(anonymous) @ fusioncharts.widgets.js:14
p.core @ fusioncharts.js:23
module @ fusioncharts.js:22
register @ fusioncharts.js:25
(anonymous) @ fusioncharts.widgets.js:13
(anonymous) @ index.js:25
FusionChartsModule.forRoot @ index.js:24
(anonymous) @ app.module.ts:40
(anonymous) @ app.module.ts:50
__webpack_require__ @ bootstrap e4c90a4…:19
(anonymous) @ main.browser.ts:4
__webpack_require__ @ bootstrap e4c90a4…:19
(anonymous) @ zone.js:1426
__webpack_require__ @ bootstrap e4c90a4…:19
(anonymous) @ bootstrap e4c90a4…:63
(anonymous) @ bootstrap e4c90a4…:63
fusioncharts.js:23Uncaught SyntaxError: #25081840 undefined Error >> Use the "new" keyword while creating a new FusionCharts object
    at p.core (http://localhost:3000/main.bundle.js:66834:156)
    at http://localhost:3000/main.bundle.js:62464:13
    at Array.forEach (native)
    at Function.FusionChartsModule.forRoot (http://localhost:3000/main.bundle.js:62463:29)
    at http://localhost:3000/main.bundle.js:63066:60
    at Object.<anonymous> (http://localhost:3000/main.bundle.js:63077:2)
    at __webpack_require__ (http://localhost:3000/main.bundle.js:20:30)
    at Object.<anonymous> (http://localhost:3000/main.bundle.js:49753:20)
    at __webpack_require__ (http://localhost:3000/main.bundle.js:20:30)
    at Object.<anonymous> (http://localhost:3000/main.bundle.js:76442:18)
p.core @ fusioncharts.js:23
(anonymous) @ index.js:25
FusionChartsModule.forRoot @ index.js:24
(anonymous) @ app.module.ts:40
(anonymous) @ app.module.ts:50
__webpack_require__ @ bootstrap e4c90a4…:19
(anonymous) @ main.browser.ts:4
__webpack_require__ @ bootstrap e4c90a4…:19
(anonymous) @ zone.js:1426
__webpack_require__ @ bootstrap e4c90a4…:19
(anonymous) @ bootstrap e4c90a4…:63
(anonymous) @ bootstrap e4c90a4…:63
fusioncharts.js:89Uncaught TypeError: a.setChartData is not a function
    at Function.<anonymous> (http://localhost:3000/main.bundle.js:66900:243)
    at z (http://localhost:3000/main.bundle.js:66844:496)
    at I (http://localhost:3000/main.bundle.js:66845:204)
    at Object.triggerEvent (http://localhost:3000/main.bundle.js:66848:358)
    at Object.g.raiseEvent (http://localhost:3000/main.bundle.js:66849:176)
    at p.core (http://localhost:3000/main.bundle.js:66835:449)
    at http://localhost:3000/main.bundle.js:62464:13
    at Array.forEach (native)
    at Function.FusionChartsModule.forRoot (http://localhost:3000/main.bundle.js:62463:29)
    at http://localhost:3000/main.bundle.js:63066:60

**Comment by jayh92** [comment]
Did you ever get a response for this from FusionCharts? I have the same situation.

**Comment by JasonHaley** [comment]
Not yet

**Comment by rohitkr** [comment]
@JasonHaley ,
For licensed files related query could you please mail to support@fusioncharts.com FusionCharts support team.

**Comment by rohitkr** [comment]
@JasonHaley,
FusionCharts have released its version [3.12.0](http://www.fusioncharts.com/version-history/), can you please try with the latest (3.12.0) files and let us know whether this issue is fixed or not?

**Comment by jayh92** [comment]
Any luck yet?

**Comment by torresdaniel11** [comment]
anything ?

**Comment by ashok1994** [comment]
@torresdaniel11 @jayh92  Please refer https://fusioncharts.github.io/angular-fusioncharts , for correct documentation for angular2 and above

**Comment by ashok1994** [comment]
https://github.com/ashok1994/angular2-seed-fusioncharts

See this repo , i have the code working , i could not find the readme for the older version

**Comment by ashok1994** [comment]
Closing this issue for now , please feel free reopen if the problem persists

**Comment by nitthi** [comment]
Hi,

I got the error below
![fchart](https://user-images.githubusercontent.com/24426876/51592094-c8ca0300-1f14-11e9-84e1-201cf88e105e.PNG)

In my local there is no error. but i upload the project to server, i got the above error.
Can anyone please help me on this

**Comment by nitthi** [comment]
> Closing this issue for now , please feel free reopen if the problem persists

**Comment by nitthi** [comment]
> Closing this issue for now , please feel free reopen if the problem persists

Hi,

I got the error below

![fchart](https://user-images.githubusercontent.com/24426876/51592399-894fe680-1f15-11e9-8527-acda117faf36.PNG)

In my local there is no error. but i upload the project to server, i got the above error.
